version: "3.8"
services:
    postgres:
        image: postgres:15
        container_name: pms-backend-db
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - main-network

networks:
    main-network:
        name: pms-main-network

volumes:
    postgres:
        name: pms-backend
